-- MySQL Script generated by MySQL Workbench
-- Wed Nov 27 14:42:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdd` DEFAULT CHARACTER SET utf8 ;
USE `bdd` ;

-- -----------------------------------------------------
-- Table `bdd`.`Produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd`.`Produits` (
  `idProduits` INT NOT NULL AUTO_INCREMENT,
  `img_prod` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prix_prod` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProduits`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd`.`Commande` (
  `idCommande` INT NOT NULL AUTO_INCREMENT,
  `libellé` VARCHAR(45) NOT NULL,
  `montant` VARCHAR(45) NOT NULL,
  `date_com` DATETIME NOT NULL,
  `Produits_idProduits` INT NOT NULL,
  PRIMARY KEY (`idCommande`),
  INDEX `fk_Commande_Produits1_idx` (`Produits_idProduits` ASC) VISIBLE,
  CONSTRAINT `fk_Commande_Produits1`
    FOREIGN KEY (`Produits_idProduits`)
    REFERENCES `bdd`.`Produits` (`idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `Produits_idProduits` INT NOT NULL,
  `Commande_idCommande` INT NOT NULL,
  PRIMARY KEY (`idClient`),
  INDEX `fk_Client_Produits_idx` (`Produits_idProduits` ASC) VISIBLE,
  INDEX `fk_Client_Commande1_idx` (`Commande_idCommande` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Produits`
    FOREIGN KEY (`Produits_idProduits`)
    REFERENCES `bdd`.`Produits` (`idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_Commande1`
    FOREIGN KEY (`Commande_idCommande`)
    REFERENCES `bdd`.`Commande` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
